name: SLR parser - Github actions
on: [push]

jobs:
  test-vit-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Replace with your Python version if needed

      - name: Install dependencies on testing environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests on PatchGenerator (shape tests and verify that data is in the correct order)
        run: pytest tests/patches.py

      - name: Run unit tests on AttentionHead module (shape and convergence tests).
        run: pytest -s tests/attention_block.py
